package com.amdocs.main;

import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;


public class OmsFulfillmentMsg implements Serializable {
	
	
	private	int	OBJID;
	private	int	DEV;
	private	Date	LAST_UPDATE;
	private	String	STATUS;
	private	String	S_STATUS;
	private	int	QUANTITY;
	private	int	CHANGE_IND;
	private	int	CHANGE_QTY;
	private	Date	COMMIT_END_DATE;
	private	String	OSS_ALT_STATUS;
	private	String	OSS_CPD;
	private	Date	OSS_SRD;
	private	int	OSS_CRM_ORDER_LINE_ID;
	private	int	OSS_SENT_TO_SF;
	private	String	OSS_SERVICEID;
	private	String	OSS_ACTION;
	private	String	OSS_ORCH_SO_ID;
	private	Date	OSS_SVC_CREATE_DATE;
	private	int	OSS_PRIORITY;
	private	int	OSS_MSI;
	private	int	OSS_MRS;
	private	String	OSS_SF_PEI_ID;
	private	String	S_OSS_SF_PEI_ID;
	private	String	OSS_MAIN_PROC_INST_ID;
	private	int	OSS_KSU_SEQUENCE_NO;
	private	int	OSS_IS_PROC_ACTIVATED;
	private	String	OSS_CHARACTERISTICS;   // clob //
	private	String	OSS_PROD_INST_ID;
	private	int	OSS_GROUP_ORDER;
	private	int	OSS_CHLD_SUBGRP_ORD;
	private	int	OSS_PRNT_SUBGRP_ORD;
	private	String	OSS_SF_CONV_ID;
	private	String	OSS_SO_ACTION;
	private	int	OSS_IS_PROC_INVOKED;
	private	Date	OSS_DUE_DATE;
	private	String	OSS_PRODUCT_ID;
	private	int	OSS_IS_PRNT_DEP;
	private	int	OSS_IS_PHANTOM;
	private	String	OSS_ORIG_ACTION;
	private	String	OSS_RM_ORDER_ITEM;
	private	int	ORDER_LINE2ORDER_ACTION;
	private	int	ORDER_LINE2OFFR_PROD;
	private	int	AFFECTED2SITE_PART;
	private	int	CHILD2ORDER_LINE;
	private	int	ORDER_LINE2MOD_LEVEL;
	private	int	ORDER_STAT2HGBST_ELM;
	private	int	OSS_STATUS2HGBST_ELM;
	private	int	OSS_GROUP2GROUP_DEP;
	private	int	OSS_DECOMPOSED2ORD_ACTION;
	private	int	OSS_ORDER_LINE2SRV_ROOT;
	private	int	OSS_ORDER_LINE2GROUP_DEP;
	private	int	OSS_SEQUENCE2PARENT_SUB_GROUP;
	private	int	OSS_SEQUENCE2CHILD_SUB_GROUP;
	private	int	OSS_ORDER_LINE2PRODUCT;
	private	int	OSS_SVC_TYPE2HGBST_ELM;
	private	int	OSS_ORDER_LINE2SVC_ORDER;
	private	int	OSS_ACTION2HGBST_ELM;
	private	int	OSS_ORIGN_CMPNT2HGBST_ELM;
	private	int	OSS_EX_RFC2INT_ROOT;
	private	int	OSS_ORDER_LINE2SUB_ORDER;
	private	int	OSS_CONDITION2HGBST_ELM;
	private	int	OSS_ACTIVITY2HGBST_ELM;
	private	int	OSS_RFC_RFA_STATUS2HGBST_ELM;
	private	int	OSS_INSTANCE_TYPE2HGBST_ELM;

	
	public int getOBJID() {
		return OBJID;
	}
	public void setOBJID(int oBJID) {
		OBJID = oBJID;
	}
	public int getDEV() {
		return DEV;
	}
	public void setDEV(int dEV) {
		DEV = dEV;
	}
	public Date getLAST_UPDATE() {
		return LAST_UPDATE;
	}
	public void setLAST_UPDATE(Date lAST_UPDATE) {
		LAST_UPDATE = lAST_UPDATE;
	}
	public String getSTATUS() {
		return STATUS;
	}
	public void setSTATUS(String sTATUS) {
		STATUS = sTATUS;
	}
	public String getS_STATUS() {
		return S_STATUS;
	}
	public void setS_STATUS(String s_STATUS) {
		S_STATUS = s_STATUS;
	}
	public int getQUANTITY() {
		return QUANTITY;
	}
	public void setQUANTITY(int qUANTITY) {
		QUANTITY = qUANTITY;
	}
	public int getCHANGE_IND() {
		return CHANGE_IND;
	}
	public void setCHANGE_IND(int cHANGE_IND) {
		CHANGE_IND = cHANGE_IND;
	}
	public int getCHANGE_QTY() {
		return CHANGE_QTY;
	}
	public void setCHANGE_QTY(int cHANGE_QTY) {
		CHANGE_QTY = cHANGE_QTY;
	}
	public Date getCOMMIT_END_DATE() {
		return COMMIT_END_DATE;
	}
	public void setCOMMIT_END_DATE(Date cOMMIT_END_DATE) {
		COMMIT_END_DATE = cOMMIT_END_DATE;
	}
	public String getOSS_ALT_STATUS() {
		return OSS_ALT_STATUS;
	}
	public void setOSS_ALT_STATUS(String oSS_ALT_STATUS) {
		OSS_ALT_STATUS = oSS_ALT_STATUS;
	}
	public String getOSS_CPD() {
		return OSS_CPD;
	}
	public void setOSS_CPD(String oSS_CPD) {
		OSS_CPD = oSS_CPD;
	}
	public Date getOSS_SRD() {
		return OSS_SRD;
	}
	public void setOSS_SRD(Date oSS_SRD) {
		OSS_SRD = oSS_SRD;
	}
	public int getOSS_CRM_ORDER_LINE_ID() {
		return OSS_CRM_ORDER_LINE_ID;
	}
	public void setOSS_CRM_ORDER_LINE_ID(int oSS_CRM_ORDER_LINE_ID) {
		OSS_CRM_ORDER_LINE_ID = oSS_CRM_ORDER_LINE_ID;
	}
	public int getOSS_SENT_TO_SF() {
		return OSS_SENT_TO_SF;
	}
	public void setOSS_SENT_TO_SF(int oSS_SENT_TO_SF) {
		OSS_SENT_TO_SF = oSS_SENT_TO_SF;
	}
	public String getOSS_SERVICEID() {
		return OSS_SERVICEID;
	}
	public void setOSS_SERVICEID(String oSS_SERVICEID) {
		OSS_SERVICEID = oSS_SERVICEID;
	}
	public String getOSS_ACTION() {
		return OSS_ACTION;
	}
	public void setOSS_ACTION(String oSS_ACTION) {
		OSS_ACTION = oSS_ACTION;
	}
	public String getOSS_ORCH_SO_ID() {
		return OSS_ORCH_SO_ID;
	}
	public void setOSS_ORCH_SO_ID(String oSS_ORCH_SO_ID) {
		OSS_ORCH_SO_ID = oSS_ORCH_SO_ID;
	}
	public Date getOSS_SVC_CREATE_DATE() {
		return OSS_SVC_CREATE_DATE;
	}
	public void setOSS_SVC_CREATE_DATE(Date oSS_SVC_CREATE_DATE) {
		OSS_SVC_CREATE_DATE = oSS_SVC_CREATE_DATE;
	}
	public int getOSS_PRIORITY() {
		return OSS_PRIORITY;
	}
	public void setOSS_PRIORITY(int oSS_PRIORITY) {
		OSS_PRIORITY = oSS_PRIORITY;
	}
	public int getOSS_MSI() {
		return OSS_MSI;
	}
	public void setOSS_MSI(int oSS_MSI) {
		OSS_MSI = oSS_MSI;
	}
	public int getOSS_MRS() {
		return OSS_MRS;
	}
	public void setOSS_MRS(int oSS_MRS) {
		OSS_MRS = oSS_MRS;
	}
	public String getOSS_SF_PEI_ID() {
		return OSS_SF_PEI_ID;
	}
	public void setOSS_SF_PEI_ID(String oSS_SF_PEI_ID) {
		OSS_SF_PEI_ID = oSS_SF_PEI_ID;
	}
	public String getS_OSS_SF_PEI_ID() {
		return S_OSS_SF_PEI_ID;
	}
	public void setS_OSS_SF_PEI_ID(String s_OSS_SF_PEI_ID) {
		S_OSS_SF_PEI_ID = s_OSS_SF_PEI_ID;
	}
	public String getOSS_MAIN_PROC_INST_ID() {
		return OSS_MAIN_PROC_INST_ID;
	}
	public void setOSS_MAIN_PROC_INST_ID(String oSS_MAIN_PROC_INST_ID) {
		OSS_MAIN_PROC_INST_ID = oSS_MAIN_PROC_INST_ID;
	}
	public int getOSS_KSU_SEQUENCE_NO() {
		return OSS_KSU_SEQUENCE_NO;
	}
	public void setOSS_KSU_SEQUENCE_NO(int oSS_KSU_SEQUENCE_NO) {
		OSS_KSU_SEQUENCE_NO = oSS_KSU_SEQUENCE_NO;
	}
	public int getOSS_IS_PROC_ACTIVATED() {
		return OSS_IS_PROC_ACTIVATED;
	}
	public void setOSS_IS_PROC_ACTIVATED(int oSS_IS_PROC_ACTIVATED) {
		OSS_IS_PROC_ACTIVATED = oSS_IS_PROC_ACTIVATED;
	}
	public String getOSS_CHARACTERISTICS() {
		return OSS_CHARACTERISTICS;
	}
	public void setOSS_CHARACTERISTICS(String oSS_CHARACTERISTICS) {
		OSS_CHARACTERISTICS = oSS_CHARACTERISTICS;
	}
	public String getOSS_PROD_INST_ID() {
		return OSS_PROD_INST_ID;
	}
	public void setOSS_PROD_INST_ID(String oSS_PROD_INST_ID) {
		OSS_PROD_INST_ID = oSS_PROD_INST_ID;
	}
	public int getOSS_GROUP_ORDER() {
		return OSS_GROUP_ORDER;
	}
	public void setOSS_GROUP_ORDER(int oSS_GROUP_ORDER) {
		OSS_GROUP_ORDER = oSS_GROUP_ORDER;
	}
	public int getOSS_CHLD_SUBGRP_ORD() {
		return OSS_CHLD_SUBGRP_ORD;
	}
	public void setOSS_CHLD_SUBGRP_ORD(int oSS_CHLD_SUBGRP_ORD) {
		OSS_CHLD_SUBGRP_ORD = oSS_CHLD_SUBGRP_ORD;
	}
	public int getOSS_PRNT_SUBGRP_ORD() {
		return OSS_PRNT_SUBGRP_ORD;
	}
	public void setOSS_PRNT_SUBGRP_ORD(int oSS_PRNT_SUBGRP_ORD) {
		OSS_PRNT_SUBGRP_ORD = oSS_PRNT_SUBGRP_ORD;
	}
	public String getOSS_SF_CONV_ID() {
		return OSS_SF_CONV_ID;
	}
	public void setOSS_SF_CONV_ID(String oSS_SF_CONV_ID) {
		OSS_SF_CONV_ID = oSS_SF_CONV_ID;
	}
	public String getOSS_SO_ACTION() {
		return OSS_SO_ACTION;
	}
	public void setOSS_SO_ACTION(String oSS_SO_ACTION) {
		OSS_SO_ACTION = oSS_SO_ACTION;
	}
	public int getOSS_IS_PROC_INVOKED() {
		return OSS_IS_PROC_INVOKED;
	}
	public void setOSS_IS_PROC_INVOKED(int oSS_IS_PROC_INVOKED) {
		OSS_IS_PROC_INVOKED = oSS_IS_PROC_INVOKED;
	}
	public Date getOSS_DUE_DATE() {
		return OSS_DUE_DATE;
	}
	public void setOSS_DUE_DATE(Date oSS_DUE_DATE) {
		OSS_DUE_DATE = oSS_DUE_DATE;
	}
	public String getOSS_PRODUCT_ID() {
		return OSS_PRODUCT_ID;
	}
	public void setOSS_PRODUCT_ID(String oSS_PRODUCT_ID) {
		OSS_PRODUCT_ID = oSS_PRODUCT_ID;
	}
	public int getOSS_IS_PRNT_DEP() {
		return OSS_IS_PRNT_DEP;
	}
	public void setOSS_IS_PRNT_DEP(int oSS_IS_PRNT_DEP) {
		OSS_IS_PRNT_DEP = oSS_IS_PRNT_DEP;
	}
	public int getOSS_IS_PHANTOM() {
		return OSS_IS_PHANTOM;
	}
	public void setOSS_IS_PHANTOM(int oSS_IS_PHANTOM) {
		OSS_IS_PHANTOM = oSS_IS_PHANTOM;
	}
	public String getOSS_ORIG_ACTION() {
		return OSS_ORIG_ACTION;
	}
	public void setOSS_ORIG_ACTION(String oSS_ORIG_ACTION) {
		OSS_ORIG_ACTION = oSS_ORIG_ACTION;
	}
	public String getOSS_RM_ORDER_ITEM() {
		return OSS_RM_ORDER_ITEM;
	}
	public void setOSS_RM_ORDER_ITEM(String oSS_RM_ORDER_ITEM) {
		OSS_RM_ORDER_ITEM = oSS_RM_ORDER_ITEM;
	}
	public int getORDER_LINE2ORDER_ACTION() {
		return ORDER_LINE2ORDER_ACTION;
	}
	public void setORDER_LINE2ORDER_ACTION(int oRDER_LINE2ORDER_ACTION) {
		ORDER_LINE2ORDER_ACTION = oRDER_LINE2ORDER_ACTION;
	}
	public int getORDER_LINE2OFFR_PROD() {
		return ORDER_LINE2OFFR_PROD;
	}
	public void setORDER_LINE2OFFR_PROD(int oRDER_LINE2OFFR_PROD) {
		ORDER_LINE2OFFR_PROD = oRDER_LINE2OFFR_PROD;
	}
	public int getAFFECTED2SITE_PART() {
		return AFFECTED2SITE_PART;
	}
	public void setAFFECTED2SITE_PART(int aFFECTED2SITE_PART) {
		AFFECTED2SITE_PART = aFFECTED2SITE_PART;
	}
	public int getCHILD2ORDER_LINE() {
		return CHILD2ORDER_LINE;
	}
	public void setCHILD2ORDER_LINE(int cHILD2ORDER_LINE) {
		CHILD2ORDER_LINE = cHILD2ORDER_LINE;
	}
	public int getORDER_LINE2MOD_LEVEL() {
		return ORDER_LINE2MOD_LEVEL;
	}
	public void setORDER_LINE2MOD_LEVEL(int oRDER_LINE2MOD_LEVEL) {
		ORDER_LINE2MOD_LEVEL = oRDER_LINE2MOD_LEVEL;
	}
	public int getORDER_STAT2HGBST_ELM() {
		return ORDER_STAT2HGBST_ELM;
	}
	public void setORDER_STAT2HGBST_ELM(int oRDER_STAT2HGBST_ELM) {
		ORDER_STAT2HGBST_ELM = oRDER_STAT2HGBST_ELM;
	}
	public int getOSS_STATUS2HGBST_ELM() {
		return OSS_STATUS2HGBST_ELM;
	}
	public void setOSS_STATUS2HGBST_ELM(int oSS_STATUS2HGBST_ELM) {
		OSS_STATUS2HGBST_ELM = oSS_STATUS2HGBST_ELM;
	}
	public int getOSS_GROUP2GROUP_DEP() {
		return OSS_GROUP2GROUP_DEP;
	}
	public void setOSS_GROUP2GROUP_DEP(int oSS_GROUP2GROUP_DEP) {
		OSS_GROUP2GROUP_DEP = oSS_GROUP2GROUP_DEP;
	}
	public int getOSS_DECOMPOSED2ORD_ACTION() {
		return OSS_DECOMPOSED2ORD_ACTION;
	}
	public void setOSS_DECOMPOSED2ORD_ACTION(int oSS_DECOMPOSED2ORD_ACTION) {
		OSS_DECOMPOSED2ORD_ACTION = oSS_DECOMPOSED2ORD_ACTION;
	}
	public int getOSS_ORDER_LINE2SRV_ROOT() {
		return OSS_ORDER_LINE2SRV_ROOT;
	}
	public void setOSS_ORDER_LINE2SRV_ROOT(int oSS_ORDER_LINE2SRV_ROOT) {
		OSS_ORDER_LINE2SRV_ROOT = oSS_ORDER_LINE2SRV_ROOT;
	}
	public int getOSS_ORDER_LINE2GROUP_DEP() {
		return OSS_ORDER_LINE2GROUP_DEP;
	}
	public void setOSS_ORDER_LINE2GROUP_DEP(int oSS_ORDER_LINE2GROUP_DEP) {
		OSS_ORDER_LINE2GROUP_DEP = oSS_ORDER_LINE2GROUP_DEP;
	}
	public int getOSS_SEQUENCE2PARENT_SUB_GROUP() {
		return OSS_SEQUENCE2PARENT_SUB_GROUP;
	}
	public void setOSS_SEQUENCE2PARENT_SUB_GROUP(int oSS_SEQUENCE2PARENT_SUB_GROUP) {
		OSS_SEQUENCE2PARENT_SUB_GROUP = oSS_SEQUENCE2PARENT_SUB_GROUP;
	}
	public int getOSS_SEQUENCE2CHILD_SUB_GROUP() {
		return OSS_SEQUENCE2CHILD_SUB_GROUP;
	}
	public void setOSS_SEQUENCE2CHILD_SUB_GROUP(int oSS_SEQUENCE2CHILD_SUB_GROUP) {
		OSS_SEQUENCE2CHILD_SUB_GROUP = oSS_SEQUENCE2CHILD_SUB_GROUP;
	}
	public int getOSS_ORDER_LINE2PRODUCT() {
		return OSS_ORDER_LINE2PRODUCT;
	}
	public void setOSS_ORDER_LINE2PRODUCT(int oSS_ORDER_LINE2PRODUCT) {
		OSS_ORDER_LINE2PRODUCT = oSS_ORDER_LINE2PRODUCT;
	}
	public int getOSS_SVC_TYPE2HGBST_ELM() {
		return OSS_SVC_TYPE2HGBST_ELM;
	}
	public void setOSS_SVC_TYPE2HGBST_ELM(int oSS_SVC_TYPE2HGBST_ELM) {
		OSS_SVC_TYPE2HGBST_ELM = oSS_SVC_TYPE2HGBST_ELM;
	}
	public int getOSS_ORDER_LINE2SVC_ORDER() {
		return OSS_ORDER_LINE2SVC_ORDER;
	}
	public void setOSS_ORDER_LINE2SVC_ORDER(int oSS_ORDER_LINE2SVC_ORDER) {
		OSS_ORDER_LINE2SVC_ORDER = oSS_ORDER_LINE2SVC_ORDER;
	}
	public int getOSS_ACTION2HGBST_ELM() {
		return OSS_ACTION2HGBST_ELM;
	}
	public void setOSS_ACTION2HGBST_ELM(int oSS_ACTION2HGBST_ELM) {
		OSS_ACTION2HGBST_ELM = oSS_ACTION2HGBST_ELM;
	}
	public int getOSS_ORIGN_CMPNT2HGBST_ELM() {
		return OSS_ORIGN_CMPNT2HGBST_ELM;
	}
	public void setOSS_ORIGN_CMPNT2HGBST_ELM(int oSS_ORIGN_CMPNT2HGBST_ELM) {
		OSS_ORIGN_CMPNT2HGBST_ELM = oSS_ORIGN_CMPNT2HGBST_ELM;
	}
	public int getOSS_EX_RFC2INT_ROOT() {
		return OSS_EX_RFC2INT_ROOT;
	}
	public void setOSS_EX_RFC2INT_ROOT(int oSS_EX_RFC2INT_ROOT) {
		OSS_EX_RFC2INT_ROOT = oSS_EX_RFC2INT_ROOT;
	}
	public int getOSS_ORDER_LINE2SUB_ORDER() {
		return OSS_ORDER_LINE2SUB_ORDER;
	}
	public void setOSS_ORDER_LINE2SUB_ORDER(int oSS_ORDER_LINE2SUB_ORDER) {
		OSS_ORDER_LINE2SUB_ORDER = oSS_ORDER_LINE2SUB_ORDER;
	}
	public int getOSS_CONDITION2HGBST_ELM() {
		return OSS_CONDITION2HGBST_ELM;
	}
	public void setOSS_CONDITION2HGBST_ELM(int oSS_CONDITION2HGBST_ELM) {
		OSS_CONDITION2HGBST_ELM = oSS_CONDITION2HGBST_ELM;
	}
	public int getOSS_ACTIVITY2HGBST_ELM() {
		return OSS_ACTIVITY2HGBST_ELM;
	}
	public void setOSS_ACTIVITY2HGBST_ELM(int oSS_ACTIVITY2HGBST_ELM) {
		OSS_ACTIVITY2HGBST_ELM = oSS_ACTIVITY2HGBST_ELM;
	}
	public int getOSS_RFC_RFA_STATUS2HGBST_ELM() {
		return OSS_RFC_RFA_STATUS2HGBST_ELM;
	}
	public void setOSS_RFC_RFA_STATUS2HGBST_ELM(int oSS_RFC_RFA_STATUS2HGBST_ELM) {
		OSS_RFC_RFA_STATUS2HGBST_ELM = oSS_RFC_RFA_STATUS2HGBST_ELM;
	}
	public int getOSS_INSTANCE_TYPE2HGBST_ELM() {
		return OSS_INSTANCE_TYPE2HGBST_ELM;
	}
	public void setOSS_INSTANCE_TYPE2HGBST_ELM(int oSS_INSTANCE_TYPE2HGBST_ELM) {
		OSS_INSTANCE_TYPE2HGBST_ELM = oSS_INSTANCE_TYPE2HGBST_ELM;
	}
	
	
	// CONSTRUCTORS //
	public OmsFulfillmentMsg(int oBJID, int dEV, Date lAST_UPDATE, String sTATUS, String s_STATUS, int qUANTITY,
			int cHANGE_IND, int cHANGE_QTY, Date cOMMIT_END_DATE, String oSS_ALT_STATUS, String oSS_CPD, Date oSS_SRD,
			int oSS_CRM_ORDER_LINE_ID, int oSS_SENT_TO_SF, String oSS_SERVICEID, String oSS_ACTION,
			String oSS_ORCH_SO_ID, Date oSS_SVC_CREATE_DATE, int oSS_PRIORITY, int oSS_MSI, int oSS_MRS,
			String oSS_SF_PEI_ID, String s_OSS_SF_PEI_ID, String oSS_MAIN_PROC_INST_ID, int oSS_KSU_SEQUENCE_NO,
			int oSS_IS_PROC_ACTIVATED, String oSS_CHARACTERISTICS, String oSS_PROD_INST_ID, int oSS_GROUP_ORDER,
			int oSS_CHLD_SUBGRP_ORD, int oSS_PRNT_SUBGRP_ORD, String oSS_SF_CONV_ID, String oSS_SO_ACTION,
			int oSS_IS_PROC_INVOKED, Date oSS_DUE_DATE, String oSS_PRODUCT_ID, int oSS_IS_PRNT_DEP, int oSS_IS_PHANTOM,
			String oSS_ORIG_ACTION, String oSS_RM_ORDER_ITEM, int oRDER_LINE2ORDER_ACTION, int oRDER_LINE2OFFR_PROD,
			int aFFECTED2SITE_PART, int cHILD2ORDER_LINE, int oRDER_LINE2MOD_LEVEL, int oRDER_STAT2HGBST_ELM,
			int oSS_STATUS2HGBST_ELM, int oSS_GROUP2GROUP_DEP, int oSS_DECOMPOSED2ORD_ACTION,
			int oSS_ORDER_LINE2SRV_ROOT, int oSS_ORDER_LINE2GROUP_DEP, int oSS_SEQUENCE2PARENT_SUB_GROUP,
			int oSS_SEQUENCE2CHILD_SUB_GROUP, int oSS_ORDER_LINE2PRODUCT, int oSS_SVC_TYPE2HGBST_ELM,
			int oSS_ORDER_LINE2SVC_ORDER, int oSS_ACTION2HGBST_ELM, int oSS_ORIGN_CMPNT2HGBST_ELM,
			int oSS_EX_RFC2INT_ROOT, int oSS_ORDER_LINE2SUB_ORDER, int oSS_CONDITION2HGBST_ELM,
			int oSS_ACTIVITY2HGBST_ELM, int oSS_RFC_RFA_STATUS2HGBST_ELM, int oSS_INSTANCE_TYPE2HGBST_ELM) {
		super();
		OBJID = oBJID;
		DEV = dEV;
		LAST_UPDATE = lAST_UPDATE;
		STATUS = sTATUS;
		S_STATUS = s_STATUS;
		QUANTITY = qUANTITY;
		CHANGE_IND = cHANGE_IND;
		CHANGE_QTY = cHANGE_QTY;
		COMMIT_END_DATE = cOMMIT_END_DATE;
		OSS_ALT_STATUS = oSS_ALT_STATUS;
		OSS_CPD = oSS_CPD;
		OSS_SRD = oSS_SRD;
		OSS_CRM_ORDER_LINE_ID = oSS_CRM_ORDER_LINE_ID;
		OSS_SENT_TO_SF = oSS_SENT_TO_SF;
		OSS_SERVICEID = oSS_SERVICEID;
		OSS_ACTION = oSS_ACTION;
		OSS_ORCH_SO_ID = oSS_ORCH_SO_ID;
		OSS_SVC_CREATE_DATE = oSS_SVC_CREATE_DATE;
		OSS_PRIORITY = oSS_PRIORITY;
		OSS_MSI = oSS_MSI;
		OSS_MRS = oSS_MRS;
		OSS_SF_PEI_ID = oSS_SF_PEI_ID;
		S_OSS_SF_PEI_ID = s_OSS_SF_PEI_ID;
		OSS_MAIN_PROC_INST_ID = oSS_MAIN_PROC_INST_ID;
		OSS_KSU_SEQUENCE_NO = oSS_KSU_SEQUENCE_NO;
		OSS_IS_PROC_ACTIVATED = oSS_IS_PROC_ACTIVATED;
		OSS_CHARACTERISTICS = oSS_CHARACTERISTICS;
		OSS_PROD_INST_ID = oSS_PROD_INST_ID;
		OSS_GROUP_ORDER = oSS_GROUP_ORDER;
		OSS_CHLD_SUBGRP_ORD = oSS_CHLD_SUBGRP_ORD;
		OSS_PRNT_SUBGRP_ORD = oSS_PRNT_SUBGRP_ORD;
		OSS_SF_CONV_ID = oSS_SF_CONV_ID;
		OSS_SO_ACTION = oSS_SO_ACTION;
		OSS_IS_PROC_INVOKED = oSS_IS_PROC_INVOKED;
		OSS_DUE_DATE = oSS_DUE_DATE;
		OSS_PRODUCT_ID = oSS_PRODUCT_ID;
		OSS_IS_PRNT_DEP = oSS_IS_PRNT_DEP;
		OSS_IS_PHANTOM = oSS_IS_PHANTOM;
		OSS_ORIG_ACTION = oSS_ORIG_ACTION;
		OSS_RM_ORDER_ITEM = oSS_RM_ORDER_ITEM;
		ORDER_LINE2ORDER_ACTION = oRDER_LINE2ORDER_ACTION;
		ORDER_LINE2OFFR_PROD = oRDER_LINE2OFFR_PROD;
		AFFECTED2SITE_PART = aFFECTED2SITE_PART;
		CHILD2ORDER_LINE = cHILD2ORDER_LINE;
		ORDER_LINE2MOD_LEVEL = oRDER_LINE2MOD_LEVEL;
		ORDER_STAT2HGBST_ELM = oRDER_STAT2HGBST_ELM;
		OSS_STATUS2HGBST_ELM = oSS_STATUS2HGBST_ELM;
		OSS_GROUP2GROUP_DEP = oSS_GROUP2GROUP_DEP;
		OSS_DECOMPOSED2ORD_ACTION = oSS_DECOMPOSED2ORD_ACTION;
		OSS_ORDER_LINE2SRV_ROOT = oSS_ORDER_LINE2SRV_ROOT;
		OSS_ORDER_LINE2GROUP_DEP = oSS_ORDER_LINE2GROUP_DEP;
		OSS_SEQUENCE2PARENT_SUB_GROUP = oSS_SEQUENCE2PARENT_SUB_GROUP;
		OSS_SEQUENCE2CHILD_SUB_GROUP = oSS_SEQUENCE2CHILD_SUB_GROUP;
		OSS_ORDER_LINE2PRODUCT = oSS_ORDER_LINE2PRODUCT;
		OSS_SVC_TYPE2HGBST_ELM = oSS_SVC_TYPE2HGBST_ELM;
		OSS_ORDER_LINE2SVC_ORDER = oSS_ORDER_LINE2SVC_ORDER;
		OSS_ACTION2HGBST_ELM = oSS_ACTION2HGBST_ELM;
		OSS_ORIGN_CMPNT2HGBST_ELM = oSS_ORIGN_CMPNT2HGBST_ELM;
		OSS_EX_RFC2INT_ROOT = oSS_EX_RFC2INT_ROOT;
		OSS_ORDER_LINE2SUB_ORDER = oSS_ORDER_LINE2SUB_ORDER;
		OSS_CONDITION2HGBST_ELM = oSS_CONDITION2HGBST_ELM;
		OSS_ACTIVITY2HGBST_ELM = oSS_ACTIVITY2HGBST_ELM;
		OSS_RFC_RFA_STATUS2HGBST_ELM = oSS_RFC_RFA_STATUS2HGBST_ELM;
		OSS_INSTANCE_TYPE2HGBST_ELM = oSS_INSTANCE_TYPE2HGBST_ELM;
	}
	
	
}
